#! /bin/bash
VERSION="$(git describe --tags $(git rev-list --tags --max-count=1))"
HASH=$(git rev-parse HEAD)

#######################################################################
## Gen Version
#######################################################################
cat >./typex/version.go <<EOF
// Warning:
//
//	This file is generated by go compiler, don't change it!!!
package typex

import "github.com/hootrhino/rhilex/utils"

var MainVersion string

type VersionInfo struct {
	ReleaseTime string
	Arch        string
	Product     string
	Dist        string
}

var License = utils.LocalLicense{
	DeviceID:          "",
	AuthorizeAdmin:    "",
	AuthorizePassword: "",
	MAC:               "",
	BeginAuthorize:    0,
	EndAuthorize:      0,
	License:           "",
}

var DefaultVersionInfo = VersionInfo{
	Product:     "COMMON",
	ReleaseTime: "$(echo $(date "+%Y-%m-%d %H:%M:%S"))",
}
var Banner = \`
  <<  RHILEX System.©                              -·
<<·   Version: ${VERSION}-${HASH:0:15}             -·
  <<  More information: https://www.hootrhino.com  -·
\`
EOF

echo "Generate Version Susseccfully"

