#! /bin/bash
VERSION="$(git describe --tags $(git rev-list --tags --max-count=1))"
HASH=$(git rev-parse --short HEAD)

#######################################################################
## Gen Version
#######################################################################
cat >./typex/version.go <<EOF
//=================
// !Warning!
//    This file is generated by go compiler, don't change it!!!
//=================
package typex


// v0.0.0: Default Develop Version
var MainVersion string = "v0.0.0"

type VersionInfo struct {
	ReleaseTime string
	Arch        string
	Product     string
	Dist        string
}


var DefaultVersionInfo = VersionInfo{
	Product:     "COMMON",
	ReleaseTime: "$(echo $(date "+%Y-%m-%d %H:%M:%S"))",
}
var Banner = \`
  <<  RHILEX System.©                              -·
<<·   Version: ${VERSION}-${HASH:0:15}             -·
  <<  More information: https://www.hootrhino.com  -·
\`
EOF

echo "[v] Generate Version Susseccfully"

