// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: aibase.proto

package aibase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIBaseService_Call_FullMethodName   = "/aibase.AIBaseService/Call"
	AIBaseService_Stream_FullMethodName = "/aibase.AIBaseService/Stream"
)

// AIBaseServiceClient is the client API for AIBaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIBaseServiceClient interface {
	// 普通请求
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// 流式请求
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error)
}

type aIBaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIBaseServiceClient(cc grpc.ClientConnInterface) AIBaseServiceClient {
	return &aIBaseServiceClient{cc}
}

func (c *aIBaseServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, AIBaseService_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIBaseServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIBaseService_ServiceDesc.Streams[0], AIBaseService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIBaseService_StreamClient = grpc.BidiStreamingClient[StreamRequest, StreamResponse]

// AIBaseServiceServer is the server API for AIBaseService service.
// All implementations must embed UnimplementedAIBaseServiceServer
// for forward compatibility.
type AIBaseServiceServer interface {
	// 普通请求
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// 流式请求
	Stream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error
	mustEmbedUnimplementedAIBaseServiceServer()
}

// UnimplementedAIBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIBaseServiceServer struct{}

func (UnimplementedAIBaseServiceServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedAIBaseServiceServer) Stream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAIBaseServiceServer) mustEmbedUnimplementedAIBaseServiceServer() {}
func (UnimplementedAIBaseServiceServer) testEmbeddedByValue()                       {}

// UnsafeAIBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIBaseServiceServer will
// result in compilation errors.
type UnsafeAIBaseServiceServer interface {
	mustEmbedUnimplementedAIBaseServiceServer()
}

func RegisterAIBaseServiceServer(s grpc.ServiceRegistrar, srv AIBaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIBaseService_ServiceDesc, srv)
}

func _AIBaseService_Call_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBaseServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIBaseService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AIBaseServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIBaseService_Stream_Handler(srv any, stream grpc.ServerStream) error {
	return srv.(AIBaseServiceServer).Stream(&grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIBaseService_StreamServer = grpc.BidiStreamingServer[StreamRequest, StreamResponse]

// AIBaseService_ServiceDesc is the grpc.ServiceDesc for AIBaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIBaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aibase.AIBaseService",
	HandlerType: (*AIBaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _AIBaseService_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AIBaseService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "aibase.proto",
}
