// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: grpc_source.proto

package rhilexrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RhilexRpc_Work_FullMethodName = "/rhilexrpc.RhilexRpc/Work"
)

// RhilexRpcClient is the client API for RhilexRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RhilexRpcClient interface {
	Work(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error)
}

type rhilexRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRhilexRpcClient(cc grpc.ClientConnInterface) RhilexRpcClient {
	return &rhilexRpcClient{cc}
}

func (c *rhilexRpcClient) Work(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, RhilexRpc_Work_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RhilexRpcServer is the server API for RhilexRpc service.
// All implementations must embed UnimplementedRhilexRpcServer
// for forward compatibility
type RhilexRpcServer interface {
	Work(context.Context, *Data) (*Response, error)
	mustEmbedUnimplementedRhilexRpcServer()
}

// UnimplementedRhilexRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRhilexRpcServer struct {
}

func (UnimplementedRhilexRpcServer) Work(context.Context, *Data) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Work not implemented")
}
func (UnimplementedRhilexRpcServer) mustEmbedUnimplementedRhilexRpcServer() {}

// UnsafeRhilexRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RhilexRpcServer will
// result in compilation errors.
type UnsafeRhilexRpcServer interface {
	mustEmbedUnimplementedRhilexRpcServer()
}

func RegisterRhilexRpcServer(s grpc.ServiceRegistrar, srv RhilexRpcServer) {
	s.RegisterService(&RhilexRpc_ServiceDesc, srv)
}

func _RhilexRpc_Work_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RhilexRpcServer).Work(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RhilexRpc_Work_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RhilexRpcServer).Work(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// RhilexRpc_ServiceDesc is the grpc.ServiceDesc for RhilexRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RhilexRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rhilexrpc.RhilexRpc",
	HandlerType: (*RhilexRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Work",
			Handler:    _RhilexRpc_Work_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_source.proto",
}
