package crontask

// CRON_TASK_TYPE
const (
	CRON_TASK_TYPE_LINUX_SHELL = "LINUX_SHELL"
)

// LINUX_SHELL Linux脚本执行器
const LINUX_SHELL = "/bin/bash"

const PERM_0777 = 0777

// CRON_RESULT_STATUS
const (
	CRON_RESULT_STATUS_RUNNING = "RUNNING"
	CRON_RESULT_STATUS_END     = "END"
)

var CRON_TASK_EANBLE = true
var CRON_TASK_DISABLE = false
