// Warning:
//
//	This file is generated by go compiler, don't change it!!!
package typex

var MainVersion string

type VersionInfo struct {
	ReleaseTime string
	Arch        string
	Product     string
	Dist        string
}

var License = LocalLicense{
	DeviceID:          "",
	AuthorizeAdmin:    "",
	AuthorizePassword: "",
	MAC:               "",
	BeginAuthorize:    0,
	EndAuthorize:      0,
	License:           "",
}

var DefaultVersionInfo = VersionInfo{
	Product:        "COMMON",
	ReleaseTime: "2024-04-27 19:58:37",
}
var Banner = `
 **  Welcome to RHILEX framework world <'_'>     -.
**   Version: v0.6.8-564982242dc0993             -.
 **  More information: https://hootrhino.github.io  -.
`
