// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: activation.proto

package activation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceActivation_ActivateDevice_FullMethodName = "/activation.DeviceActivation/ActivateDevice"
)

// DeviceActivationClient is the client API for DeviceActivation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceActivationClient interface {
	ActivateDevice(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*ActivationResponse, error)
}

type deviceActivationClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceActivationClient(cc grpc.ClientConnInterface) DeviceActivationClient {
	return &deviceActivationClient{cc}
}

func (c *deviceActivationClient) ActivateDevice(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*ActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivationResponse)
	err := c.cc.Invoke(ctx, DeviceActivation_ActivateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceActivationServer is the server API for DeviceActivation service.
// All implementations must embed UnimplementedDeviceActivationServer
// for forward compatibility.
type DeviceActivationServer interface {
	ActivateDevice(context.Context, *ActivationRequest) (*ActivationResponse, error)
	mustEmbedUnimplementedDeviceActivationServer()
}

// UnimplementedDeviceActivationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceActivationServer struct{}

func (UnimplementedDeviceActivationServer) ActivateDevice(context.Context, *ActivationRequest) (*ActivationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateDevice not implemented")
}
func (UnimplementedDeviceActivationServer) mustEmbedUnimplementedDeviceActivationServer() {}
func (UnimplementedDeviceActivationServer) testEmbeddedByValue()                          {}

// UnsafeDeviceActivationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceActivationServer will
// result in compilation errors.
type UnsafeDeviceActivationServer interface {
	mustEmbedUnimplementedDeviceActivationServer()
}

func RegisterDeviceActivationServer(s grpc.ServiceRegistrar, srv DeviceActivationServer) {
	// If the following call pancis, it indicates UnimplementedDeviceActivationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceActivation_ServiceDesc, srv)
}

func _DeviceActivation_ActivateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceActivationServer).ActivateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceActivation_ActivateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceActivationServer).ActivateDevice(ctx, req.(*ActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceActivation_ServiceDesc is the grpc.ServiceDesc for DeviceActivation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceActivation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activation.DeviceActivation",
	HandlerType: (*DeviceActivationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateDevice",
			Handler:    _DeviceActivation_ActivateDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activation.proto",
}
